docs:
  - AGENTS.md

agent:
  tone: concise
  verbosity: low
  preambles: true

planning:
  use_plan_when: multi_step
  max_steps: 6

rules:
  tests_first: true
  show_patch_preview: true
  error_style: result_or_typed_error
  function_style: pure_small
  typing: explicit_no_any
  security_checks: validate_and_sanitize

commands:
  setup: npm ci
  dev: npm run dev
  build: npm run build
  start: npm start
  test: npm test
  test_unit: npm run test:unit
  test_integration: npm run test:integration
  coverage: npm run test:coverage
  lint: npm run lint
  lint_fix: npm run lint:fix