services:
  cubicagent-openai:
    build: .
    ports:
      - "${AGENT_PORT:-3000}:${AGENT_PORT:-3000}"
    environment:
      - AGENT_PORT=${AGENT_PORT:-3000}
      - AGENT_NAME=${AGENT_NAME:-CubicAgent-OpenAI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-1}
      - OPENAI_SESSION_MAX_TOKENS=${OPENAI_SESSION_MAX_TOKENS:-2048}
      - CUBICLER_URL=${CUBICLER_URL:-http://localhost:1503}
      - AGENT_TIMEOUT=${AGENT_TIMEOUT:-10000}
      - AGENT_MAX_RETRIES=${AGENT_MAX_RETRIES:-3}
      - AGENT_SESSION_MAX_ITERATION=${AGENT_SESSION_MAX_ITERATION:-10}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${AGENT_PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cubicagent-network

networks:
  cubicagent-network:
    driver: bridge
